# .travis.yml for R projects.
#
# https://travis-ci.org/flr/FLCore

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

warnings_are_errors: false

language: r

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release

sudo: false

addons:
  apt:
    packages:
      - libgsl-dev

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
