# https://ci.appveyor.com/project/flr/FLPKG
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    USE_RTOOLS: true
    R_BUILD_ARGS: --no-multiarch
    R_ARCH: x64

  matrix:
  - R_VERSION: release

platform: x64

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests
  - travis-tool.sh dump_logs
  - 7z a Logs.zip *.Rcheck\00*.*
  - appveyor PushArtifact Logs.zip
  - appveyor PushArtifact Bits.zip

on_failure:
  - travis-tool.sh dump_logs
  - 7z a Logs.zip *.Rcheck\00*.*
  - appveyor PushArtifact Logs.zip

artifacts:
  - path: '*.Rcheck\**\00*.log'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
